### ISSUE TITLE
[Question] Setup Caldera & Empire in RTO

### ISSUE THREAD

**Issue by me009** [hunters-forge/mordor#19]
Any tips on how to start caldera and Empire in the RTO box?
Pls what the docker command to do this? I'm struggling to get it to work...

**Comment by Cyb3rWard0g** [comment]
Hey @me009 , sorry for the late response. There were a few commits pushed at the beginning of the week. and I just updated the Caldera docker image I created. Let me know if it works now after the update. To start Empire or Caldera, you can follow the steps taken in the script available here: https://github.com/hunters-forge/Blacksmith/blob/master/aws/mordor/cfn-files/scripts/default/Install-C2s.sh#L91-L101 . remember you can only run one C2 at the time. A few ports overlap. Let me know if those commands work.
