### ISSUE TITLE
kafkacat not available in ubuntu 19.10+

### ISSUE THREAD

**Issue by jwsy** [hunters-forge/mordor#22]
We weren't able to install kafkacat in ubuntu 19.10. We were able to get around this by following these instructions posted in https://github.com/dbcli/mssql-cli/issues/252.

I think this could be helpful on https://mordordatasets.com/import_mordor.html

```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
```

**Comment by Cyb3rWard0g** [comment]
Thank you very much @jwsy ! sorry I missed this.  I will add this to the wiki in the next updates. thank you again 🙏
