### ISSUE TITLE
Audit policy configuration

### ISSUE THREAD

**Issue by 0xffca** [hunters-forge/mordor#23]
Hello!

Great project! I was wondering if you could dump somewhere in the documentation how the audit policy for the DC and also on clients are configured. 
It would help a bunch to have this information.

Best,
\f

**Comment by Cyb3rWard0g** [comment]
Hey @0xffca ! sorry for the late response. I thought I had answered this via my phone. The audit configurations are found in the projects' website. If you scroll down in this page you will find the Security Auditing script used to enable certain audit categories and the Sysmon configuration used to filter out a lot of noise. https://mordordatasets.com/mordor_shire.html I hope this helps!

**Comment by 0xffca** [comment]
Thank you very much! Sorry for the noise, I will close this ticket.
Really great project!

**Comment by xiaodupi-zyq** [comment]
https://mordordatasets.com/mordor_shire.html 。now it is 404. where can i find it?

**Comment by Cyb3rWard0g** [comment]
Links worked now. Thank you for the heads up. I revamped the projects behind the datasets to build the environments and changed the resources structure.
