### ISSUE TITLE
[QUESTION] Does Mordor support ECS fields mapping

### ISSUE THREAD

**Issue by H1L021** [hunters-forge/mordor#26]
Hello Hunters,

I have an elastic cluster up and running and i was kinda interested in using Mordor's datasets in order to test rules created with signals and elastalert to display a Detection Capabilities Dashboard. My question is does the mordor project support ECS since I am mapping all of my event with it.

Thank you for your great work

**Comment by Cyb3rWard0g** [comment]
Hey @H1L021 ! Several of the Small datasets were shipped by Winlogbeat to a kafka broker to be exported. It has the raw Winlogbeat schema `winlog.` I believe. You should be fine ingesting it.

**Comment by barvhaim** [comment]
@H1L021 - I made a script to convert Mordor's large raw events to follow winlogbeat ECS schema 7.8, available here - https://github.com/barvhaim/mordor2ecs/tree/master

**Comment by Cyb3rWard0g** [comment]
Thank you @barvhaim !
