### ISSUE TITLE
APT29 Day 1 and Day 2 Dataset files are missing.

### ISSUE THREAD

**Issue by halilozturkci** [hunters-forge/mordor#27]
Got some error whet tried to download APT29 dataset.

apt29_evals_day1_manual.zip->Size mismatch 
apt29_evals_day2_manual.zip->404 File not Found, 404 response

**Comment by Cyb3rWard0g** [comment]
Thank you for the heads up!

apt29_evals_day1_manual.zip is 367M after decompressing the file:

`367M May  1 23:28 apt29_evals_day1_manual_2020-05-01225525.json`

I fixed the second link with the commit below. Thank you again!
