### ISSUE TITLE
Using Mordor

### ISSUE THREAD

**Issue by veeral-patel** [hunters-forge/mordor#28]
Hey - thanks for this great project! I have to say, I don't fully understand it...I see it provides JSON log files that were created after running attacks, but how should I use this information as an defender? I read the README and the introductory blog post but I still don't understand.

**Comment by Cyb3rWard0g** [comment]
Hey @veeral-patel ! This is a great example. Every single playbook/notebook leverages datasets from mordor to perform research and validate analytics developed https://threathunterplaybook.com/notebooks/windows/windows.html
